import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service — SnapCode",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black">
      <div className="max-w-3xl mx-auto px-4 py-12 sm:py-16">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-gray-400 hover:text-white mb-8 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to SnapCode
        </Link>

        <h1 className="text-3xl sm:text-4xl font-bold mb-8">Terms of Service</h1>

        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-gray-400">
          <p><strong className="text-white">Last updated:</strong> February 2026</p>

          <h2 className="text-xl font-semibold text-white mt-8">1. What SnapCode Does</h2>
          <p>
            SnapCode is a free tool that converts UI screenshots into code using AI (Google Gemini).
            You upload a screenshot, choose a framework, and get generated code.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8">2. Free Tier</h2>
          <p>
            The free tier allows 5 code generations per day. No signup is required.
            We reserve the right to adjust usage limits at any time.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8">3. Your Content</h2>
          <p>
            Screenshots you upload are sent to Google Gemini AI for processing. We do not store
            your screenshots or generated code on our servers. All results are stored locally
            in your browser.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8">4. Generated Code</h2>
          <p>
            The code generated by SnapCode is yours to use however you want — personal projects,
            commercial projects, client work. No attribution required. However, we make no
            guarantees about the accuracy, completeness, or fitness of the generated code.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8">5. Fair Use</h2>
          <p>
            Don&apos;t abuse the service — no automated scraping, no spamming the API, no attempting
            to bypass rate limits. We reserve the right to block IPs that violate fair use.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8">6. No Warranty</h2>
          <p>
            SnapCode is provided &quot;as is&quot; without any warranty. We&apos;re not liable for
            any damages arising from your use of the service.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8">7. Changes</h2>
          <p>
            We may update these terms at any time. Continued use of SnapCode means you accept
            the updated terms.
          </p>

          <p className="text-gray-600 mt-12">
            Questions? Contact us at hello@snapcode.dev
          </p>
        </div>
      </div>
      <Footer />
    </div>
  );
}
