/**
 * Shared HTML builders — used by ResponsivePreview (iframe) and ExportDropdown (Copy as HTML).
 * Extracted from components/ResponsivePreview.tsx to avoid circular imports.
 */

function cleanReactCode(code: string): string {
  let cleaned = code;
  cleaned = cleaned.replace(/<!--\s*Generated by SnapCode\.ai\s*-->\s*/g, "");
  cleaned = cleaned.replace(/['"]use (client|server)['"];?\s*/g, "");
  cleaned = cleaned.replace(/^import\s+type\s+\{[^}]*\}\s+from\s+['"][^'"]*['"];?\s*$/gm, "");

  const reactImportMatch = cleaned.match(
    /import\s+(?:React\s*,\s*)?\{([^}]+)\}\s+from\s+['"]react['"];?/
  );
  let destructured = "";
  if (reactImportMatch) {
    const names = reactImportMatch[1]
      .split(",")
      .map((n) => n.trim())
      .filter((n) => n && !n.startsWith("type "));
    if (names.length > 0) {
      destructured = `const { ${names.join(", ")} } = React;\n`;
    }
  }

  cleaned = cleaned.replace(/^import\s+.*?from\s+['"].*?['"];?\s*$/gm, "");
  cleaned = cleaned.replace(/^import\s+['"].*?['"];?\s*$/gm, "");
  cleaned = cleaned.replace(/^(export\s+)?(interface|type)\s+\w[\s\S]*?^\}/gm, "");
  cleaned = cleaned.replace(/^type\s+\w+\s*=\s*[^;]+;?\s*$/gm, "");
  cleaned = cleaned.replace(/export\s+default\s+/g, "");
  cleaned = cleaned.replace(/export\s+/g, "");
  cleaned = cleaned.replace(/^export\s*\{[^}]*\};?\s*$/gm, "");
  cleaned = destructured + cleaned;
  return cleaned.trim();
}

function buildReactHtml(code: string): string {
  const cleaned = cleanReactCode(code);
  const safeCode = cleaned.replace(/<\/script/gi, "<\\/script");

  // Fallback: find any export default function/class name
  let componentName = "";
  const exportMatch = code.match(/export\s+default\s+(?:function|class)\s+(\w+)/);
  if (exportMatch) {
    componentName = exportMatch[1];
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <style>
    body { margin: 0; font-family: system-ui, -apple-system, sans-serif; }
    * { box-sizing: border-box; }
  </style>
</head>
<body>
  <div id="root"></div>
  <script>
    window.Link = function Link(props) {
      return React.createElement('a', { href: props.href || '#', className: props.className || '', style: props.style, onClick: function(e) { e.preventDefault(); } }, props.children);
    };
    window.Image = function ImageComponent(props) {
      return React.createElement('img', { src: props.src || 'https://placehold.co/' + (props.width || 400) + 'x' + (props.height || 300), alt: props.alt || '', width: props.width, height: props.height, className: props.className || '', style: props.style });
    };
    window.LucideIcon = function(props) {
      return React.createElement('span', { className: props.className || 'w-5 h-5 inline-block', style: { display: 'inline-block', width: '1em', height: '1em' } });
    };
  </script>
  <script type="text/babel" data-presets="react,typescript">
    ${safeCode}

    (function() {
      var __names = [
        typeof App !== 'undefined' && App, typeof Home !== 'undefined' && Home,
        typeof Page !== 'undefined' && Page, typeof Main !== 'undefined' && Main,
        typeof Component !== 'undefined' && Component, typeof Index !== 'undefined' && Index,
        typeof Layout !== 'undefined' && Layout, typeof Hero !== 'undefined' && Hero,
        typeof Card !== 'undefined' && Card, typeof Landing !== 'undefined' && Landing,
        typeof Dashboard !== 'undefined' && Dashboard, typeof Header !== 'undefined' && Header,
        typeof Footer !== 'undefined' && Footer, typeof Navbar !== 'undefined' && Navbar,
        typeof Sidebar !== 'undefined' && Sidebar, typeof Form !== 'undefined' && Form,
        typeof Login !== 'undefined' && Login, typeof Signup !== 'undefined' && Signup,
        typeof Profile !== 'undefined' && Profile, typeof Settings !== 'undefined' && Settings,
      ];
      var __Component = __names.find(function(c) { return c && typeof c === 'function'; });
      ${componentName ? `if (!__Component) { try { if (typeof ${componentName} === 'function') __Component = ${componentName}; } catch(e) {} }` : ""}
      if (__Component) {
        ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(__Component));
      } else {
        document.getElementById('root').innerHTML = '<div style="padding:20px;color:#888;text-align:center;">No component found to render.</div>';
      }
    })();
  </script>
</body>
</html>`;
}

function buildVueHtml(code: string): string {
  let clean = code.replace(/<!--\s*Generated by SnapCode\.ai\s*-->\s*/g, "");
  const templateMatch = clean.match(/<template>([\s\S]*?)<\/template>/);
  const styleMatch = clean.match(/<style[^>]*>([\s\S]*?)<\/style>/);
  const template = templateMatch ? templateMatch[1].trim() : clean.replace(/<script[\s\S]*?<\/script>/g, "").replace(/<style[\s\S]*?<\/style>/g, "").trim();
  const styles = styleMatch ? styleMatch[1] : "";
  const safeTemplate = template.replace(/<\/script/gi, "<\\/script");
  const safeStyles = styles.replace(/<\/script/gi, "<\\/script");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://unpkg.com/vue@3/dist/vue.global.prod.js"></script>
  <style>body{margin:0;font-family:system-ui,sans-serif}${safeStyles}</style>
</head>
<body>
  <div id="app">${safeTemplate}</div>
  <script>
    try { var app = Vue.createApp({ data: function() { return {}; } }); app.mount('#app'); } catch(e) { console.error('Vue mount error:', e); }
  </script>
</body>
</html>`;
}

function buildSvelteHtml(code: string): string {
  let clean = code.replace(/<!--\s*Generated by SnapCode\.ai\s*-->\s*/g, "");
  const styleMatch = clean.match(/<style[^>]*>([\s\S]*?)<\/style>/);
  const styles = styleMatch ? styleMatch[1] : "";
  let html = clean.replace(/<script[\s\S]*?<\/script>/g, "").replace(/<style[\s\S]*?<\/style>/g, "");
  // Remove Svelte control flow blocks
  html = html.replace(/\{[#:/][^}]+\}/g, "");
  html = html.replace(/on:[a-z]+=\{[^}]*\}/g, "").replace(/bind:[a-z]+=\{[^}]*\}/g, "");
  // Replace simple expressions with empty string (they won't render in plain HTML)
  html = html.replace(/\{([a-zA-Z_]\w*(?:\.\w+)*)\}/g, "");
  const safeHtml = html.replace(/<\/script/gi, "<\\/script");
  const safeStyles = styles.replace(/<\/script/gi, "<\\/script");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <style>body{margin:0;font-family:system-ui,sans-serif}${safeStyles}</style>
</head>
<body>${safeHtml.trim()}</body>
</html>`;
}

function buildHtmlTailwind(code: string): string {
  let clean = code.replace(/<!--\s*Generated by SnapCode\.ai\s*-->\s*/g, "");
  if (clean.toLowerCase().includes("<!doctype") || clean.toLowerCase().includes("<html")) {
    if (!clean.includes("tailwindcss")) {
      clean = clean.replace("</head>", `<script src="https://cdn.tailwindcss.com"></script>\n</head>`);
    }
    return clean;
  }
  const safeCode = clean.replace(/<\/script/gi, "<\\/script");
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <style>body{margin:0;font-family:system-ui,sans-serif}</style>
</head>
<body>${safeCode}</body>
</html>`;
}

function buildBootstrapHtml(code: string): string {
  let clean = code.replace(/<!--\s*Generated by SnapCode\.ai\s*-->\s*/g, "");
  if (clean.toLowerCase().includes("<!doctype") || clean.toLowerCase().includes("<html")) {
    if (!clean.toLowerCase().includes("bootstrap")) {
      clean = clean.replace(/<\/head>/i, `<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">\n<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>\n</head>`);
    }
    if (!clean.includes("viewport")) {
      clean = clean.replace(/<head>/i, `<head>\n<meta name="viewport" content="width=device-width, initial-scale=1.0">`);
    }
    return clean;
  }
  const safeCode = clean.replace(/<\/script/gi, "<\\/script");
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <style>body{margin:0;font-family:system-ui,sans-serif}</style>
</head>
<body>${safeCode}</body>
</html>`;
}

export function buildPreviewHtml(code: string, framework: string): string {
  switch (framework) {
    case "react-tailwind":
    case "nextjs":
      return buildReactHtml(code);
    case "vue":
      return buildVueHtml(code);
    case "svelte":
      return buildSvelteHtml(code);
    case "bootstrap":
      return buildBootstrapHtml(code);
    default:
      return buildHtmlTailwind(code);
  }
}
