export function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    if (!file.size) return resolve("");
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const result = reader.result as string;
      // Remove the data:image/xxx;base64, prefix
      const base64 = result.split(",")[1] || "";
      resolve(base64);
    };
    reader.onerror = (error) => reject(error);
  });
}

export function getMimeType(file: File): string {
  return file.type || "image/png";
}

export function cleanCode(text: string): string {
  let code = text.trim();
  // Remove markdown code fences anywhere
  code = code.replace(/^```[\w]*\n?/m, "");
  code = code.replace(/\n?```\s*$/m, "");
  return code.trim();
}

// Note: addWatermark uses HTML comment syntax. This is appropriate because
// the generate route always produces HTML output.
export function addWatermark(code: string): string {
  return `<!-- Generated by SnapCode.ai -->\n${code}`;
}
